# Generated by Django 4.0.3 on 2022-03-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=150)),
                ('work_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iswc', models.CharField(max_length=13, unique=True)),
                ('source', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=505)),
                ('contributors', models.ManyToManyField(related_name='csv_files', to='repertoire.contributor')),
                ('proprietary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietary_id', to='repertoire.proprietary')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_files', to='repertoire.file')),
                ('works', models.ManyToManyField(related_name='work_files', to='repertoire.work')),
            ],
        ),
    ]
