# Generated by Django 4.0.3 on 2022-03-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkFiles',
        ),
    ]
