# Generated by Django 4.0.3 on 2022-03-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0002_delete_workfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_files', to='repertoire.file')),
                ('works', models.ManyToManyField(related_name='work_files', to='repertoire.work')),
            ],
        ),
    ]
