# Generated by Django 4.0.3 on 2022-03-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_workfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkFiles',
            new_name='WorksFile',
        ),
    ]
