# Generated by Django 4.0.3 on 2022-03-09 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0004_rename_workfiles_worksfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_works', to='repertoire.file')),
                ('works', models.ManyToManyField(related_name='file_works', to='repertoire.work')),
            ],
        ),
        migrations.DeleteModel(
            name='WorksFile',
        ),
    ]
