# Generated by Django 4.0.3 on 2022-03-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0005_fileworks_delete_worksfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietary',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
