# Generated by Django 4.0.3 on 2022-05-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0008_alter_work_iswc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryname', models.CharField(max_length=50)),
                ('stores_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CountryStores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_stores', to='repertoire.country')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=50)),
                ('workers_count', models.IntegerField(default=1)),
                ('square_meters', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='fileworks',
            name='file',
        ),
        migrations.RemoveField(
            model_name='fileworks',
            name='works',
        ),
        migrations.RemoveField(
            model_name='work',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='work',
            name='proprietary',
        ),
        migrations.RenameModel(
            old_name='Contributor',
            new_name='Manager',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='FileWorks',
        ),
        migrations.DeleteModel(
            name='Proprietary',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.AddField(
            model_name='store',
            name='managers',
            field=models.ManyToManyField(related_name='store_managers', to='repertoire.manager'),
        ),
        migrations.AddField(
            model_name='countrystores',
            name='stores',
            field=models.ManyToManyField(related_name='country_stores', to='repertoire.store'),
        ),
    ]
